{% set name = "opentelemetry-util-http" %}
{% set version = "0.49b0" %}
{% set python_min = python_min|default("3.8") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_util_http-{{ version }}.tar.gz
  sha256: 02928496afcffd58a7c15baf99d2cedae9b8325a8ac52b0d0877b2e8f936dd1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - opentelemetry
    - opentelemetry.util
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/util/opentelemetry-util-http
  summary: Web util for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
